# permissions for end users to edit khulnasoftcsps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: khulnasoftcsp-editor-role
rules:
- apiGroups:
  - operator.khulnasoftsec.com
  resources:
  - khulnasoftcsps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.khulnasoftsec.com
  resources:
  - khulnasoftcsps/status
  verbs:
  - get
