# permissions for end users to view khulnasoftgateways.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: khulnasoftgateway-viewer-role
rules:
- apiGroups:
  - operator.khulnasoftsec.com
  resources:
  - khulnasoftgateways
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.khulnasoftsec.com
  resources:
  - khulnasoftgateways/status
  verbs:
  - get
