# permissions for end users to view khulnasoftcsps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: khulnasoftcsp-viewer-role
rules:
- apiGroups:
  - operator.khulnasoftsec.com
  resources:
  - khulnasoftcsps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.khulnasoftsec.com
  resources:
  - khulnasoftcsps/status
  verbs:
  - get
