# permissions for end users to view khulnasoftenforcers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: khulnasoftenforcer-viewer-role
rules:
- apiGroups:
  - operator.khulnasoftsec.com
  resources:
  - khulnasoftenforcers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.khulnasoftsec.com
  resources:
  - khulnasoftenforcers/status
  verbs:
  - get
