# permissions for end users to edit khulnasoftservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: khulnasoftserver-editor-role
rules:
- apiGroups:
  - operator.khulnasoftsec.com
  resources:
  - khulnasoftservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.khulnasoftsec.com
  resources:
  - khulnasoftservers/status
  verbs:
  - get
