# permissions for end users to edit khulnasoftdatabases.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: khulnasoftdatabase-editor-role
rules:
- apiGroups:
  - operator.khulnasoftsec.com
  resources:
  - khulnasoftdatabases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.khulnasoftsec.com
  resources:
  - khulnasoftdatabases/status
  verbs:
  - get
