# permissions for end users to view khulnasoftstarboards.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: khulnasoftstarboard-viewer-role
rules:
- apiGroups:
  - khulnasoft.github.io
  resources:
  - khulnasoftstarboards
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - khulnasoft.github.io
  resources:
  - khulnasoftstarboards/status
  verbs:
  - get
