//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KhulnasoftCommon) DeepCopyInto(out *KhulnasoftCommon) {
	*out = *in
	if in.AdminPassword != nil {
		in, out := &in.AdminPassword, &out.AdminPassword
		*out = new(Khulnasoftret)
		**out = **in
	}
	if in.KhulnasoftLicense != nil {
		in, out := &in.KhulnasoftLicense, &out.KhulnasoftLicense
		*out = new(Khulnasoftret)
		**out = **in
	}
	if in.DatabaseSecret != nil {
		in, out := &in.DatabaseSecret, &out.DatabaseSecret
		*out = new(Khulnasoftret)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KhulnasoftCommon.
func (in *KhulnasoftCommon) DeepCopy() *KhulnasoftCommon {
	if in == nil {
		return nil
	}
	out := new(KhulnasoftCommon)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KhulnasoftCsp) DeepCopyInto(out *KhulnasoftCsp) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KhulnasoftCsp.
func (in *KhulnasoftCsp) DeepCopy() *KhulnasoftCsp {
	if in == nil {
		return nil
	}
	out := new(KhulnasoftCsp)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KhulnasoftCsp) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KhulnasoftCspList) DeepCopyInto(out *KhulnasoftCspList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KhulnasoftCsp, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KhulnasoftCspList.
func (in *KhulnasoftCspList) DeepCopy() *KhulnasoftCspList {
	if in == nil {
		return nil
	}
	out := new(KhulnasoftCspList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KhulnasoftCspList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KhulnasoftCspSpec) DeepCopyInto(out *KhulnasoftCspSpec) {
	*out = *in
	if in.Infrastructure != nil {
		in, out := &in.Infrastructure, &out.Infrastructure
		*out = new(KhulnasoftInfrastructure)
		**out = **in
	}
	if in.Common != nil {
		in, out := &in.Common, &out.Common
		*out = new(KhulnasoftCommon)
		(*in).DeepCopyInto(*out)
	}
	if in.RegistryData != nil {
		in, out := &in.RegistryData, &out.RegistryData
		*out = new(KhulnasoftDockerRegistry)
		**out = **in
	}
	if in.ExternalDb != nil {
		in, out := &in.ExternalDb, &out.ExternalDb
		*out = new(KhulnasoftDatabaseInformation)
		**out = **in
	}
	if in.AuditDB != nil {
		in, out := &in.AuditDB, &out.AuditDB
		*out = new(AuditDBInformation)
		(*in).DeepCopyInto(*out)
	}
	if in.DbService != nil {
		in, out := &in.DbService, &out.DbService
		*out = new(KhulnasoftService)
		(*in).DeepCopyInto(*out)
	}
	if in.GatewayService != nil {
		in, out := &in.GatewayService, &out.GatewayService
		*out = new(KhulnasoftService)
		(*in).DeepCopyInto(*out)
	}
	if in.ServerService != nil {
		in, out := &in.ServerService, &out.ServerService
		*out = new(KhulnasoftService)
		(*in).DeepCopyInto(*out)
	}
	if in.Enforcer != nil {
		in, out := &in.Enforcer, &out.Enforcer
		*out = new(KhulnasoftEnforcerDetailes)
		**out = **in
	}
	if in.ServerEnvs != nil {
		in, out := &in.ServerEnvs, &out.ServerEnvs
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.GatewayEnvs != nil {
		in, out := &in.GatewayEnvs, &out.GatewayEnvs
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ServerConfigMapData != nil {
		in, out := &in.ServerConfigMapData, &out.ServerConfigMapData
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.DeployKubeEnforcer != nil {
		in, out := &in.DeployKubeEnforcer, &out.DeployKubeEnforcer
		*out = new(KhulnasoftKubeEnforcerDetails)
		**out = **in
	}
	if in.EnforcerUpdateApproved != nil {
		in, out := &in.EnforcerUpdateApproved, &out.EnforcerUpdateApproved
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KhulnasoftCspSpec.
func (in *KhulnasoftCspSpec) DeepCopy() *KhulnasoftCspSpec {
	if in == nil {
		return nil
	}
	out := new(KhulnasoftCspSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KhulnasoftCspStatus) DeepCopyInto(out *KhulnasoftCspStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KhulnasoftCspStatus.
func (in *KhulnasoftCspStatus) DeepCopy() *KhulnasoftCspStatus {
	if in == nil {
		return nil
	}
	out := new(KhulnasoftCspStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KhulnasoftDatabase) DeepCopyInto(out *KhulnasoftDatabase) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KhulnasoftDatabase.
func (in *KhulnasoftDatabase) DeepCopy() *KhulnasoftDatabase {
	if in == nil {
		return nil
	}
	out := new(KhulnasoftDatabase)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KhulnasoftDatabase) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KhulnasoftDatabaseInformation) DeepCopyInto(out *KhulnasoftDatabaseInformation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KhulnasoftDatabaseInformation.
func (in *KhulnasoftDatabaseInformation) DeepCopy() *KhulnasoftDatabaseInformation {
	if in == nil {
		return nil
	}
	out := new(KhulnasoftDatabaseInformation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KhulnasoftDatabaseList) DeepCopyInto(out *KhulnasoftDatabaseList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KhulnasoftDatabase, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KhulnasoftDatabaseList.
func (in *KhulnasoftDatabaseList) DeepCopy() *KhulnasoftDatabaseList {
	if in == nil {
		return nil
	}
	out := new(KhulnasoftDatabaseList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KhulnasoftDatabaseList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KhulnasoftDatabaseSpec) DeepCopyInto(out *KhulnasoftDatabaseSpec) {
	*out = *in
	if in.Infrastructure != nil {
		in, out := &in.Infrastructure, &out.Infrastructure
		*out = new(KhulnasoftInfrastructure)
		**out = **in
	}
	if in.Common != nil {
		in, out := &in.Common, &out.Common
		*out = new(KhulnasoftCommon)
		(*in).DeepCopyInto(*out)
	}
	if in.DbService != nil {
		in, out := &in.DbService, &out.DbService
		*out = new(KhulnasoftService)
		(*in).DeepCopyInto(*out)
	}
	if in.AuditDB != nil {
		in, out := &in.AuditDB, &out.AuditDB
		*out = new(AuditDBInformation)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KhulnasoftDatabaseSpec.
func (in *KhulnasoftDatabaseSpec) DeepCopy() *KhulnasoftDatabaseSpec {
	if in == nil {
		return nil
	}
	out := new(KhulnasoftDatabaseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KhulnasoftDatabaseStatus) DeepCopyInto(out *KhulnasoftDatabaseStatus) {
	*out = *in
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KhulnasoftDatabaseStatus.
func (in *KhulnasoftDatabaseStatus) DeepCopy() *KhulnasoftDatabaseStatus {
	if in == nil {
		return nil
	}
	out := new(KhulnasoftDatabaseStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KhulnasoftDockerRegistry) DeepCopyInto(out *KhulnasoftDockerRegistry) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KhulnasoftDockerRegistry.
func (in *KhulnasoftDockerRegistry) DeepCopy() *KhulnasoftDockerRegistry {
	if in == nil {
		return nil
	}
	out := new(KhulnasoftDockerRegistry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KhulnasoftEnforcer) DeepCopyInto(out *KhulnasoftEnforcer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KhulnasoftEnforcer.
func (in *KhulnasoftEnforcer) DeepCopy() *KhulnasoftEnforcer {
	if in == nil {
		return nil
	}
	out := new(KhulnasoftEnforcer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KhulnasoftEnforcer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KhulnasoftEnforcerDetailes) DeepCopyInto(out *KhulnasoftEnforcerDetailes) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KhulnasoftEnforcerDetailes.
func (in *KhulnasoftEnforcerDetailes) DeepCopy() *KhulnasoftEnforcerDetailes {
	if in == nil {
		return nil
	}
	out := new(KhulnasoftEnforcerDetailes)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KhulnasoftEnforcerList) DeepCopyInto(out *KhulnasoftEnforcerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KhulnasoftEnforcer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KhulnasoftEnforcerList.
func (in *KhulnasoftEnforcerList) DeepCopy() *KhulnasoftEnforcerList {
	if in == nil {
		return nil
	}
	out := new(KhulnasoftEnforcerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KhulnasoftEnforcerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KhulnasoftEnforcerSpec) DeepCopyInto(out *KhulnasoftEnforcerSpec) {
	*out = *in
	if in.Infrastructure != nil {
		in, out := &in.Infrastructure, &out.Infrastructure
		*out = new(KhulnasoftInfrastructure)
		**out = **in
	}
	if in.Common != nil {
		in, out := &in.Common, &out.Common
		*out = new(KhulnasoftCommon)
		(*in).DeepCopyInto(*out)
	}
	if in.EnforcerService != nil {
		in, out := &in.EnforcerService, &out.EnforcerService
		*out = new(KhulnasoftService)
		(*in).DeepCopyInto(*out)
	}
	if in.Gateway != nil {
		in, out := &in.Gateway, &out.Gateway
		*out = new(KhulnasoftGatewayInformation)
		**out = **in
	}
	if in.Secret != nil {
		in, out := &in.Secret, &out.Secret
		*out = new(Khulnasoftret)
		**out = **in
	}
	if in.Envs != nil {
		in, out := &in.Envs, &out.Envs
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.EnforcerUpdateApproved != nil {
		in, out := &in.EnforcerUpdateApproved, &out.EnforcerUpdateApproved
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KhulnasoftEnforcerSpec.
func (in *KhulnasoftEnforcerSpec) DeepCopy() *KhulnasoftEnforcerSpec {
	if in == nil {
		return nil
	}
	out := new(KhulnasoftEnforcerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KhulnasoftEnforcerStatus) DeepCopyInto(out *KhulnasoftEnforcerStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KhulnasoftEnforcerStatus.
func (in *KhulnasoftEnforcerStatus) DeepCopy() *KhulnasoftEnforcerStatus {
	if in == nil {
		return nil
	}
	out := new(KhulnasoftEnforcerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KhulnasoftGateway) DeepCopyInto(out *KhulnasoftGateway) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KhulnasoftGateway.
func (in *KhulnasoftGateway) DeepCopy() *KhulnasoftGateway {
	if in == nil {
		return nil
	}
	out := new(KhulnasoftGateway)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KhulnasoftGateway) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KhulnasoftGatewayInformation) DeepCopyInto(out *KhulnasoftGatewayInformation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KhulnasoftGatewayInformation.
func (in *KhulnasoftGatewayInformation) DeepCopy() *KhulnasoftGatewayInformation {
	if in == nil {
		return nil
	}
	out := new(KhulnasoftGatewayInformation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KhulnasoftGatewayList) DeepCopyInto(out *KhulnasoftGatewayList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KhulnasoftGateway, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KhulnasoftGatewayList.
func (in *KhulnasoftGatewayList) DeepCopy() *KhulnasoftGatewayList {
	if in == nil {
		return nil
	}
	out := new(KhulnasoftGatewayList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KhulnasoftGatewayList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KhulnasoftGatewaySpec) DeepCopyInto(out *KhulnasoftGatewaySpec) {
	*out = *in
	if in.Infrastructure != nil {
		in, out := &in.Infrastructure, &out.Infrastructure
		*out = new(KhulnasoftInfrastructure)
		**out = **in
	}
	if in.Common != nil {
		in, out := &in.Common, &out.Common
		*out = new(KhulnasoftCommon)
		(*in).DeepCopyInto(*out)
	}
	if in.GatewayService != nil {
		in, out := &in.GatewayService, &out.GatewayService
		*out = new(KhulnasoftService)
		(*in).DeepCopyInto(*out)
	}
	if in.ExternalDb != nil {
		in, out := &in.ExternalDb, &out.ExternalDb
		*out = new(KhulnasoftDatabaseInformation)
		**out = **in
	}
	if in.AuditDB != nil {
		in, out := &in.AuditDB, &out.AuditDB
		*out = new(AuditDBInformation)
		(*in).DeepCopyInto(*out)
	}
	if in.Envs != nil {
		in, out := &in.Envs, &out.Envs
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KhulnasoftGatewaySpec.
func (in *KhulnasoftGatewaySpec) DeepCopy() *KhulnasoftGatewaySpec {
	if in == nil {
		return nil
	}
	out := new(KhulnasoftGatewaySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KhulnasoftGatewayStatus) DeepCopyInto(out *KhulnasoftGatewayStatus) {
	*out = *in
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KhulnasoftGatewayStatus.
func (in *KhulnasoftGatewayStatus) DeepCopy() *KhulnasoftGatewayStatus {
	if in == nil {
		return nil
	}
	out := new(KhulnasoftGatewayStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KhulnasoftImage) DeepCopyInto(out *KhulnasoftImage) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KhulnasoftImage.
func (in *KhulnasoftImage) DeepCopy() *KhulnasoftImage {
	if in == nil {
		return nil
	}
	out := new(KhulnasoftImage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KhulnasoftInfrastructure) DeepCopyInto(out *KhulnasoftInfrastructure) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KhulnasoftInfrastructure.
func (in *KhulnasoftInfrastructure) DeepCopy() *KhulnasoftInfrastructure {
	if in == nil {
		return nil
	}
	out := new(KhulnasoftInfrastructure)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KhulnasoftKubeEnforcer) DeepCopyInto(out *KhulnasoftKubeEnforcer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KhulnasoftKubeEnforcer.
func (in *KhulnasoftKubeEnforcer) DeepCopy() *KhulnasoftKubeEnforcer {
	if in == nil {
		return nil
	}
	out := new(KhulnasoftKubeEnforcer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KhulnasoftKubeEnforcer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KhulnasoftKubeEnforcerConfig) DeepCopyInto(out *KhulnasoftKubeEnforcerConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KhulnasoftKubeEnforcerConfig.
func (in *KhulnasoftKubeEnforcerConfig) DeepCopy() *KhulnasoftKubeEnforcerConfig {
	if in == nil {
		return nil
	}
	out := new(KhulnasoftKubeEnforcerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KhulnasoftKubeEnforcerDetails) DeepCopyInto(out *KhulnasoftKubeEnforcerDetails) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KhulnasoftKubeEnforcerDetails.
func (in *KhulnasoftKubeEnforcerDetails) DeepCopy() *KhulnasoftKubeEnforcerDetails {
	if in == nil {
		return nil
	}
	out := new(KhulnasoftKubeEnforcerDetails)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KhulnasoftKubeEnforcerList) DeepCopyInto(out *KhulnasoftKubeEnforcerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KhulnasoftKubeEnforcer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KhulnasoftKubeEnforcerList.
func (in *KhulnasoftKubeEnforcerList) DeepCopy() *KhulnasoftKubeEnforcerList {
	if in == nil {
		return nil
	}
	out := new(KhulnasoftKubeEnforcerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KhulnasoftKubeEnforcerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KhulnasoftKubeEnforcerSpec) DeepCopyInto(out *KhulnasoftKubeEnforcerSpec) {
	*out = *in
	if in.Infrastructure != nil {
		in, out := &in.Infrastructure, &out.Infrastructure
		*out = new(KhulnasoftInfrastructure)
		**out = **in
	}
	out.Config = in.Config
	if in.RegistryData != nil {
		in, out := &in.RegistryData, &out.RegistryData
		*out = new(KhulnasoftDockerRegistry)
		**out = **in
	}
	if in.ImageData != nil {
		in, out := &in.ImageData, &out.ImageData
		*out = new(KhulnasoftImage)
		**out = **in
	}
	if in.EnforcerUpdateApproved != nil {
		in, out := &in.EnforcerUpdateApproved, &out.EnforcerUpdateApproved
		*out = new(bool)
		**out = **in
	}
	if in.KubeEnforcerService != nil {
		in, out := &in.KubeEnforcerService, &out.KubeEnforcerService
		*out = new(KhulnasoftService)
		(*in).DeepCopyInto(*out)
	}
	if in.Envs != nil {
		in, out := &in.Envs, &out.Envs
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DeployStarboard != nil {
		in, out := &in.DeployStarboard, &out.DeployStarboard
		*out = new(KhulnasoftStarboardDetails)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KhulnasoftKubeEnforcerSpec.
func (in *KhulnasoftKubeEnforcerSpec) DeepCopy() *KhulnasoftKubeEnforcerSpec {
	if in == nil {
		return nil
	}
	out := new(KhulnasoftKubeEnforcerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KhulnasoftKubeEnforcerStatus) DeepCopyInto(out *KhulnasoftKubeEnforcerStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KhulnasoftKubeEnforcerStatus.
func (in *KhulnasoftKubeEnforcerStatus) DeepCopy() *KhulnasoftKubeEnforcerStatus {
	if in == nil {
		return nil
	}
	out := new(KhulnasoftKubeEnforcerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KhulnasoftLogin) DeepCopyInto(out *KhulnasoftLogin) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KhulnasoftLogin.
func (in *KhulnasoftLogin) DeepCopy() *KhulnasoftLogin {
	if in == nil {
		return nil
	}
	out := new(KhulnasoftLogin)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KhulnasoftScanner) DeepCopyInto(out *KhulnasoftScanner) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KhulnasoftScanner.
func (in *KhulnasoftScanner) DeepCopy() *KhulnasoftScanner {
	if in == nil {
		return nil
	}
	out := new(KhulnasoftScanner)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KhulnasoftScanner) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KhulnasoftScannerCliScale) DeepCopyInto(out *KhulnasoftScannerCliScale) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KhulnasoftScannerCliScale.
func (in *KhulnasoftScannerCliScale) DeepCopy() *KhulnasoftScannerCliScale {
	if in == nil {
		return nil
	}
	out := new(KhulnasoftScannerCliScale)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KhulnasoftScannerList) DeepCopyInto(out *KhulnasoftScannerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KhulnasoftScanner, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KhulnasoftScannerList.
func (in *KhulnasoftScannerList) DeepCopy() *KhulnasoftScannerList {
	if in == nil {
		return nil
	}
	out := new(KhulnasoftScannerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KhulnasoftScannerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KhulnasoftScannerSpec) DeepCopyInto(out *KhulnasoftScannerSpec) {
	*out = *in
	if in.Infrastructure != nil {
		in, out := &in.Infrastructure, &out.Infrastructure
		*out = new(KhulnasoftInfrastructure)
		**out = **in
	}
	if in.Common != nil {
		in, out := &in.Common, &out.Common
		*out = new(KhulnasoftCommon)
		(*in).DeepCopyInto(*out)
	}
	if in.ScannerService != nil {
		in, out := &in.ScannerService, &out.ScannerService
		*out = new(KhulnasoftService)
		(*in).DeepCopyInto(*out)
	}
	if in.Login != nil {
		in, out := &in.Login, &out.Login
		*out = new(KhulnasoftLogin)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KhulnasoftScannerSpec.
func (in *KhulnasoftScannerSpec) DeepCopy() *KhulnasoftScannerSpec {
	if in == nil {
		return nil
	}
	out := new(KhulnasoftScannerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KhulnasoftScannerStatus) DeepCopyInto(out *KhulnasoftScannerStatus) {
	*out = *in
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KhulnasoftScannerStatus.
func (in *KhulnasoftScannerStatus) DeepCopy() *KhulnasoftScannerStatus {
	if in == nil {
		return nil
	}
	out := new(KhulnasoftScannerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Khulnasoftret) DeepCopyInto(out *Khulnasoftret) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Khulnasoftret.
func (in *Khulnasoftret) DeepCopy() *Khulnasoftret {
	if in == nil {
		return nil
	}
	out := new(Khulnasoftret)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KhulnasoftServer) DeepCopyInto(out *KhulnasoftServer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KhulnasoftServer.
func (in *KhulnasoftServer) DeepCopy() *KhulnasoftServer {
	if in == nil {
		return nil
	}
	out := new(KhulnasoftServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KhulnasoftServer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KhulnasoftServerList) DeepCopyInto(out *KhulnasoftServerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KhulnasoftServer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KhulnasoftServerList.
func (in *KhulnasoftServerList) DeepCopy() *KhulnasoftServerList {
	if in == nil {
		return nil
	}
	out := new(KhulnasoftServerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KhulnasoftServerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KhulnasoftServerSpec) DeepCopyInto(out *KhulnasoftServerSpec) {
	*out = *in
	if in.Infrastructure != nil {
		in, out := &in.Infrastructure, &out.Infrastructure
		*out = new(KhulnasoftInfrastructure)
		**out = **in
	}
	if in.Common != nil {
		in, out := &in.Common, &out.Common
		*out = new(KhulnasoftCommon)
		(*in).DeepCopyInto(*out)
	}
	if in.ServerService != nil {
		in, out := &in.ServerService, &out.ServerService
		*out = new(KhulnasoftService)
		(*in).DeepCopyInto(*out)
	}
	if in.ExternalDb != nil {
		in, out := &in.ExternalDb, &out.ExternalDb
		*out = new(KhulnasoftDatabaseInformation)
		**out = **in
	}
	if in.AuditDB != nil {
		in, out := &in.AuditDB, &out.AuditDB
		*out = new(AuditDBInformation)
		(*in).DeepCopyInto(*out)
	}
	if in.Enforcer != nil {
		in, out := &in.Enforcer, &out.Enforcer
		*out = new(KhulnasoftEnforcerDetailes)
		**out = **in
	}
	if in.Envs != nil {
		in, out := &in.Envs, &out.Envs
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ConfigMapData != nil {
		in, out := &in.ConfigMapData, &out.ConfigMapData
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KhulnasoftServerSpec.
func (in *KhulnasoftServerSpec) DeepCopy() *KhulnasoftServerSpec {
	if in == nil {
		return nil
	}
	out := new(KhulnasoftServerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KhulnasoftServerStatus) DeepCopyInto(out *KhulnasoftServerStatus) {
	*out = *in
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KhulnasoftServerStatus.
func (in *KhulnasoftServerStatus) DeepCopy() *KhulnasoftServerStatus {
	if in == nil {
		return nil
	}
	out := new(KhulnasoftServerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KhulnasoftService) DeepCopyInto(out *KhulnasoftService) {
	*out = *in
	if in.ImageData != nil {
		in, out := &in.ImageData, &out.ImageData
		*out = new(KhulnasoftImage)
		**out = **in
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.LivenessProbe != nil {
		in, out := &in.LivenessProbe, &out.LivenessProbe
		*out = new(v1.Probe)
		(*in).DeepCopyInto(*out)
	}
	if in.ReadinessProbe != nil {
		in, out := &in.ReadinessProbe, &out.ReadinessProbe
		*out = new(v1.Probe)
		(*in).DeepCopyInto(*out)
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(v1.Affinity)
		(*in).DeepCopyInto(*out)
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.VolumeMounts != nil {
		in, out := &in.VolumeMounts, &out.VolumeMounts
		*out = make([]v1.VolumeMount, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Volumes != nil {
		in, out := &in.Volumes, &out.Volumes
		*out = make([]v1.Volume, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KhulnasoftService.
func (in *KhulnasoftService) DeepCopy() *KhulnasoftService {
	if in == nil {
		return nil
	}
	out := new(KhulnasoftService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KhulnasoftStarboardConfig) DeepCopyInto(out *KhulnasoftStarboardConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KhulnasoftStarboardConfig.
func (in *KhulnasoftStarboardConfig) DeepCopy() *KhulnasoftStarboardConfig {
	if in == nil {
		return nil
	}
	out := new(KhulnasoftStarboardConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KhulnasoftStarboardDetails) DeepCopyInto(out *KhulnasoftStarboardDetails) {
	*out = *in
	if in.Infrastructure != nil {
		in, out := &in.Infrastructure, &out.Infrastructure
		*out = new(KhulnasoftInfrastructure)
		**out = **in
	}
	if in.StarboardService != nil {
		in, out := &in.StarboardService, &out.StarboardService
		*out = new(KhulnasoftService)
		(*in).DeepCopyInto(*out)
	}
	out.Config = in.Config
	if in.RegistryData != nil {
		in, out := &in.RegistryData, &out.RegistryData
		*out = new(KhulnasoftDockerRegistry)
		**out = **in
	}
	if in.ImageData != nil {
		in, out := &in.ImageData, &out.ImageData
		*out = new(KhulnasoftImage)
		**out = **in
	}
	if in.Envs != nil {
		in, out := &in.Envs, &out.Envs
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KhulnasoftStarboardDetails.
func (in *KhulnasoftStarboardDetails) DeepCopy() *KhulnasoftStarboardDetails {
	if in == nil {
		return nil
	}
	out := new(KhulnasoftStarboardDetails)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuditDBInformation) DeepCopyInto(out *AuditDBInformation) {
	*out = *in
	if in.AuditDBSecret != nil {
		in, out := &in.AuditDBSecret, &out.AuditDBSecret
		*out = new(Khulnasoftret)
		**out = **in
	}
	if in.Data != nil {
		in, out := &in.Data, &out.Data
		*out = new(KhulnasoftDatabaseInformation)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuditDBInformation.
func (in *AuditDBInformation) DeepCopy() *AuditDBInformation {
	if in == nil {
		return nil
	}
	out := new(AuditDBInformation)
	in.DeepCopyInto(out)
	return out
}
